[project]
name = "django-organizations"
authors = [
  { name="Ben Lopatin", email="ben@benlopatin.com" },
]
description = "Group accounts for Django"
readme = "README.rst"
requires-python = ">=3.10"
license = "BSD-3-Clause"
license-files = ["LICENSE"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 5.2",
    "Framework :: Django :: 6.0",
    "Framework :: Django :: 6.1",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = [
    "Django>=4.2",
    "django-extensions>=2.0.8",
]
dynamic = ["version"]

[project.urls]
"Source" = "https://github.com/bennylope/django-organizations"
"Issues" = "https://github.com/bennylope/django-organizations/issues"
"Documentation" = "https://django-organizations.readthedocs.io/en/latest/"

[project.optional-dependencies]
docs = [
    "Sphinx>=7.2",
    "furo>=2023.9.10",
]

[dependency-groups]
tests = [
    "pytest>=6.0",
    "coverage",
    "pytest-django>=3.0.0",
    "pytest-cov>=2.4.0",
    # Required to test default models
    "django-extensions>=2.0.8",
    "django-autoslug>=1.9.8",
    # Required for mocking signals
    "mock-django==0.6.10",
]
dev = [
    {include-group = "tests"},
    "ruff<0.16",
    "tox",
    "pre-commit",
]

[build-system]
requires = ["hatchling>=1.27"]
build-backend = "hatchling.build"

[tool.hatch.build]
sources = ["src"]
directory = "dist/"

[tool.hatch.version]
path = "src/organizations/__init__.py"

[tool.hatch.build.targets.wheel]
only-include = ["src/organizations"]
packages = ["src/organizations"]

[tool.ruff]
extend-exclude = ["**/migrations/*"]

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = ["I"]

[tool.ruff.lint.isort]
force-single-line = true
known-first-party = ["organizations"]
section-order = ["future", "standard-library", "django", "third-party", "first-party", "local-folder"]

[tool.ruff.lint.isort.sections]
django = ["django"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--cov=organizations --cov-report=term"

[tool.coverage.run]
branch = true
source = ["organizations"]
omit = ["*/migrations/*"]
